// Generated by https://quicktype.io

export interface GetAllProps {
  count: number;
  next: string;
  previous: string;
  results: GetAllResult[];
}

export interface GetAllResult {
  name: string;
  url: string;
}
